//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vectorize.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Vectorize.Resources.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CEA001_Title {
            get {
                return ResourceManager.GetString("CEA001_Title", resourceCulture);
            }
        }
        
        internal static string CEA001_MessageFormat {
            get {
                return ResourceManager.GetString("CEA001_MessageFormat", resourceCulture);
            }
        }
        
        internal static string CEA001_Description {
            get {
                return ResourceManager.GetString("CEA001_Description", resourceCulture);
            }
        }
        
        internal static string CEA001_Category {
            get {
                return ResourceManager.GetString("CEA001_Category", resourceCulture);
            }
        }
        
        internal static string CEA002_Title {
            get {
                return ResourceManager.GetString("CEA002_Title", resourceCulture);
            }
        }
        
        internal static string CEA002_Category {
            get {
                return ResourceManager.GetString("CEA002_Category", resourceCulture);
            }
        }
        
        internal static string CEA002_Description {
            get {
                return ResourceManager.GetString("CEA002_Description", resourceCulture);
            }
        }
        
        internal static string CEA002_MessageFormat {
            get {
                return ResourceManager.GetString("CEA002_MessageFormat", resourceCulture);
            }
        }
        
        internal static string CEA003_Title {
            get {
                return ResourceManager.GetString("CEA003_Title", resourceCulture);
            }
        }
        
        internal static string CEA003_Category {
            get {
                return ResourceManager.GetString("CEA003_Category", resourceCulture);
            }
        }
        
        internal static string CEA003_Description {
            get {
                return ResourceManager.GetString("CEA003_Description", resourceCulture);
            }
        }
        
        internal static string CEA003_MessageFormat {
            get {
                return ResourceManager.GetString("CEA003_MessageFormat", resourceCulture);
            }
        }
    }
}
